default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: wechat_starter_development

test:
  <<: *default
  database: wechat_starter_test

production:
  <<: *default
  database: wechat_starter_production
  username: wechat_starter
  password: <%= ENV['WECHAT_STARTER_DATABASE_PASSWORD'] %>
